// Code generated by logcopter-gen; DO NOT EDIT.

package oakgitdb

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.oak-git-db.pkg.oakgitdb")
